# Generated by Django 5.1.4 on 2025-01-08 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_count', models.PositiveIntegerField(default=0, help_text='Number of applications')),
                ('application_cost', models.DecimalField(decimal_places=2, default=0.0, help_text='Cost per application', max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the applicant', max_length=255)),
                ('contact', models.CharField(help_text='Contact information of the applicant', max_length=50)),
                ('consultation_request_time', models.DateTimeField(help_text='Requested consultation time')),
                ('application_date', models.DateTimeField(auto_now_add=True, help_text='Date of application')),
                ('consultation_result', models.CharField(choices=[('Pending', 'Pending'), ('Declined', 'Declined'), ('Interested', 'Interested')], default='Pending', help_text='Result of the consultation', max_length=50)),
                ('memo', models.TextField(blank=True, help_text='Additional notes or memo', null=True)),
                ('application', models.ForeignKey(help_text='Related application', on_delete=django.db.models.deletion.CASCADE, related_name='details', to='landing.application')),
            ],
        ),
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the landing page', max_length=255)),
                ('url', models.CharField(help_text='URL of the landing page', max_length=500)),
                ('ad_platform', models.CharField(help_text='Advertising platform associated with the landing page', max_length=255)),
                ('start_date', models.DateField(help_text='Advertisement start date')),
                ('end_date', models.DateField(blank=True, default=None, help_text='Advertisement end date', null=True)),
                ('ad_cost', models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Total advertisement cost', max_digits=10, null=True)),
                ('html_content', models.TextField(blank=True, help_text='HTML content of the landing page', null=True)),
                ('user', models.ForeignKey(default=1, help_text='The user who owns this landing page', on_delete=django.db.models.deletion.CASCADE, related_name='landing_pages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='landing_page',
            field=models.ForeignKey(help_text='Related landing page', on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='landing.landingpage'),
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_count', models.PositiveIntegerField(default=0, help_text='Number of visits')),
                ('visit_cost', models.DecimalField(decimal_places=2, default=0.0, help_text='Cost per visit', max_digits=10)),
                ('bounce_count', models.PositiveIntegerField(default=0, help_text='Number of bounces')),
                ('landing_page', models.ForeignKey(help_text='Related landing page', on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='landing.landingpage')),
            ],
        ),
        migrations.CreateModel(
            name='VisitDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('PC', 'PC'), ('Mobile', 'Mobile')], help_text='Device type of the visitor', max_length=50)),
                ('ip_address', models.GenericIPAddressField(help_text='IP address of the visitor')),
                ('session_start', models.DateTimeField(help_text='Session start time')),
                ('session_end', models.DateTimeField(help_text='Session end time')),
                ('exit_y_coordinate', models.PositiveIntegerField(blank=True, help_text='Y coordinate of the page where the visitor exited', null=True)),
                ('visit', models.ForeignKey(help_text='Related visit', on_delete=django.db.models.deletion.CASCADE, related_name='details', to='landing.visit')),
            ],
        ),
    ]
