# Generated by Django 5.1.4 on 2025-01-06 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_landingpage_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='html_content',
            field=models.TextField(blank=True, help_text='HTML content of the landing page', null=True),
        ),
    ]
