# Generated by Django 5.1.4 on 2025-01-06 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_landingpage_html_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpage',
            name='ad_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Total advertisement cost', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='end_date',
            field=models.DateField(blank=True, default=None, help_text='Advertisement end date', null=True),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='url',
            field=models.CharField(help_text='URL of the landing page', max_length=500),
        ),
    ]
