# Generated by Django 5.1.4 on 2025-01-08 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='advertiser_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='광고주명'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='contact_person',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='담당자'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='media_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='매체명'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='membership_level',
            field=models.IntegerField(choices=[(1, 'Bronze'), (2, 'Silver'), (3, 'Gold'), (4, 'Platinum')], default=1, verbose_name='회원 등급'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='전화번호'),
        ),
        migrations.CreateModel(
            name='AdvertisingAgency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_name', models.CharField(max_length=255, verbose_name='광고대행사명')),
                ('contact_person', models.CharField(max_length=255, verbose_name='담당자')),
                ('phone_number', models.CharField(max_length=20, verbose_name='전화번호')),
                ('email', models.EmailField(max_length=254, verbose_name='이메일')),
                ('is_active', models.BooleanField(default=True, verbose_name='진행 여부')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='메모')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertising_agencies', to=settings.AUTH_USER_MODEL, verbose_name='회원')),
            ],
        ),
    ]
